version: "3.8"
services:
  postgres_server:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: aroundme
      POSTGRES_USER: postgres # change this in production!
      POSTGRES_PASSWORD: fauzan # change this in production!
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - adminer-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - postgres_server
    networks:
      - adminer-network

  aroundme:
    image: developerfauzan/aroundme:latest
    env_file:
      - .env.production.local
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - postgres_server
      - adminer
    networks:
      - adminer-network

volumes:
  postgres-data:

networks:
  adminer-network:
